[phases.setup]
nixPkgs = [
  "python311",
  "xvfb",
  "libgbm",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib",
  "mesa",
  "expat",
  "libxkbcommon"
]

[phases.postInstall]
cmds = ["python -m playwright install chromium"]
